export const data = [
    {
        id: 1,
        title: "Blog Crypto",
        content: "",
        image: "blogcrypto.png",
        langage: ["HTML", "CSS", "JS"],
        website: "https://blog-crypto.vercel.app",
        github: "https://github.com/MelvinSilva/crypto-blog",
        info: "My first project with HTML, CSS and JS",
    },
    {
        id: 2,
        title: "LM - Expertise & Consulting",
        content: "",
        image: "lmexpertise.png",
        langage: ["HTML", "CSS", "JS", "BOOTSTRAP"],
        website: "https://lmexpertise.com",
        info: "Showcase website for a consulting and expertise agency",
    },
    {
        id: 3,
        title: "Mood Moove",
        content: "",
        image: "moodmood.png",
        langage: ["REACT", "SCSS", "API"],
        website: "https://mood-moove.vercel.app/",
        github: "https://github.com/MelvinSilva/mood-moove",
        info: "Project to search for events in Paris. Adding reviews is currently not working.",
    },
    {
        id: 4,
        title: "Wiki-Player",
        content: "",
        image: "wikiplayer.png",
        langage: ["REACT.JS", "SCSS", "API"],
        website: "https://wiki-player.vercel.app/",
        github: "https://github.com/MelvinSilva/wiki-player",
        info: "Project to find high-level athletes"
    },
    {
        id: 5,
        title: "TicTacToe PSG",
        content: "",
        image: "tictactoepsg.png",
        langage: ["REACT.JS", "SCSS"],
        website: "https://melvinsilva.github.io/tictactoe-psg/",
        github: "https://github.com/MelvinSilva/tictactoe-psg",
        info: "As its name suggests: Tic Tac Toe"
    },
    {
        id: 6,
        title: "Destination RHR",
        content: "",
        image: "destination-rhr.png",
        langage: ["REACT.JS", "SCSS", "NODE.JS"],
        website: "https://destination-rhr-2.vercel.app/",
        info: "Fictional Full stack project for a company. No database working.",
    },
    {
        id: 7,
        title: "Tennis-Ratio",
        content: "",
        image: "tennis-ratio.png",
        langage: ["REACT.JS", "CSS"],
        website: "https://tennis-ratio.vercel.app",
        github: "https://github.com/MelvinSilva/tennis-ratio",
        info: "Project to calculate a ratio.",
    },
    {
        id: 8,
        title: "My Portfolio",
        content: "",
        image: "no-image.png",
        langage: ["REACT.JS", "SCSS", "TAILWIND"],
        website: "https://melvinsilva.tech",
        github: "https://github.com/MelvinSilva/portfolio-react",
        info: "My current website which presents my portfolio",
    },
]

export const stackData = [
    {
        id: 1,
        title: "HTML",
        image: "html5-without-wordmark-color.svg",
    },
    {
        id: 2,
        title: "CSS",
        image: "css-3-seeklogo.com.svg",
    },
    {
        id: 3,
        title: "JS",
        image: "javascript-js-seeklogo.com.svg",
    },
    {
        id: 4,
        title: "REACT",
        image: "react-1-logo-png-transparent.png",
    },
    {
        id: 5,
        title: "ANGULAR",
        image: "angular-seeklogo.com.svg",
    },
    {
        id: 6,
        title: "BOOTSTRAP",
        image: "bootstrap-seeklogo.com.svg",
    },
    {
        id: 7,
        title: "NODE.JS",
        image: "expressjs.jpeg",
    },
    {
        id: 8,
        title: "POSTGRESQL",
        image: "postgresql-seeklogo.com.svg",
    },
    {
        id: 9,
        title: "FIGMA",
        image: "figma-seeklogo.com.svg",
    },
    {
        id: 10,
        title: "PHOTOSHOP",
        image: "adobe-photoshop-seeklogo.com.svg",
    },
    {
        id: 11,
        title: "ILLUSTRATOR",
        image: "adobe-illustrator-seeklogo.com.svg",
    },
    {
        id: 12,
        title: "NEXT.JS",
        image: "nextjs.png",
    },
]